export const FETCH_COMMUNICATION_START = 'FETCH_COMMUNICATION_START'
export const FETCH_COMMUNICATION_SUCCESS = 'FETCH_COMMUNICATION_SUCCESS'
export const FETCH_COMMUNICATION_FAILURE = 'FETCH_COMMUNICATION_FAILURE'
